version: "3.9"
services:
  pyspark-python:
    container_name: pyspark-python
    image: jupyter/pyspark-notebook:hadoop-3.2
    ports:
    - "8888:8888"
    - "4040:4040"  
    - "4041:4041"
    volumes:
    - ./src:/home/jovyan/work